version: "3.9"

networks:
  my-network:

services:
  my-mysql:
    image: mysql:8
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: inventory
      MYSQL_USER: root
      MYSQL_PASSWORD: admin1234
    ports:
      - "3307:3307"    # Exposed as 3307 on host to avoid conflicts
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .           # Build from local Dockerfile
    container_name: springboot-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql:3307/inventory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin1234
    ports:
      - "8080:8080"
    depends_on:
      - my-mysql
    networks:
      - my-network

volumes:
  mysql-data: